version: '3.9'

services:
  db:
    restart: always
    image: postgres
    container_name: db
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pg_data
    volumes:
      - pg_data:/var/lib/postgresql/data/pg_data
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: app
    build: .
    tty: true
    command: bash -c "python skymarket/manage.py makemigrations
      && python skymarket/manage.py migrate
      && python skymarket/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_data: